web:
  image: nginx:latest
  ports:
    - "80:80"

app:
  image: httpd:latest
  ports:
    - "81:80"

myweb:
  image: ${REG_LOC}/app1/web:latest
  auth:
    username: ${REG_USR}
    password: ${REG_PWD}
  ports:
    - "82:80"
