version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    image: httpd:latest
    ports:
      - "81:80"

  myweb:
    image: "${REG_LOC}/app1/web:${APP_VERSION}"
    ports:
      - "82:80"
